name: Game of life testing 

on: push 

jobs: 
  game-of-life-test: 
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: false # No detiene los demás trabajos si uno falla
      matrix: 
        java: [ '17', '21', '25' ] 
        os: [ ubuntu-latest, windows-latest ] 

    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v4 

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5.1 
        with: 
          maven-version: 3.8.2 

      - name: Set up JDK
        uses: actions/setup-java@v4 
        with: 
          distribution: 'temurin' 
          java-version: ${{ matrix.java }}

      - name: Maven test 
        run: mvn test

