name: Game of life testing 

on: push 

jobs: 
  game-of-life-test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v4 

      # Configuración de Maven específica
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5.1 
        with: 
          maven-version: 3.8.2 

      # Configuración de Java específica
      - name: Set up JDK 17
        uses: actions/setup-java@v5 
        with: 
          distribution: 'temurin' 
          java-version: '17' 

      # Ahora ya puedes ejecutar los tests con las versiones configuradas
      - name: Maven test 
        run: mvn test

